apiVersion: v2
name: kubemod
description: KubeMod is a universal Kubernetes mutating operator.
version: 0.1.6
appVersion: "0.13.0"
home: https://github.com/kubemod/kubemod
sources:
  - https://github.com/kubemod/kubemod
maintainers:
  - name: desaintmartin
    email: cedric@desaintmartin.fr
  - name: vassilvk
